export const DEFAULT_STAMPS = [
  { id: 'hospital',  emoji: '🏥',      label: '病院' },
  { id: 'friends',   emoji: '👭',      label: '友達' },
  { id: 'movie',     emoji: '🎬',      label: '映画' },
  { id: 'shopping',  emoji: '🛍️',     label: '買い物' },
  { id: 'travel',    emoji: '✈️',      label: '旅行' },
  { id: 'family',    emoji: '👨‍👩‍👧',    label: '家族' },
  { id: 'restaurant',emoji: '🍽️',     label: '外食' },
  { id: 'book',      emoji: '📚',      label: '読書' },
  { id: 'exercise',  emoji: '🏃',      label: '運動' },
  { id: 'medicine',  emoji: '💊',      label: '薬' },
  { id: 'birthday',  emoji: '🎂',      label: '誕生日' },
  { id: 'hanami',    emoji: '🌸',      label: 'お花見' },
  { id: 'cafe',      emoji: '☕',      label: 'カフェ' },
  { id: 'music',     emoji: '🎵',      label: '音楽' },
  { id: 'game',      emoji: '🎮',      label: 'ゲーム' },
  { id: 'pet',       emoji: '🐾',      label: 'ペット' },
  { id: 'relax',     emoji: '🌿',      label: 'リラックス' },
  { id: 'effort',    emoji: '💪',      label: 'がんばった' },
  { id: 'sleep',     emoji: '😴',      label: '睡眠' },
  { id: 'goodday',   emoji: '🌈',      label: 'いい日' },
]
